"""Generates Blosc reference vectors with numcodecs (which wraps c-blosc).

Dev-time tool only -- numcodecs is NOT a Falcon dependency, exactly like libaec
for the hdf5 module's szip vectors. Install with:  pip install numcodecs
Run from the repo root:  python tools/fixtures/gen_blosc_vectors.py

Writes core/src/test/resources/fixtures/blosc_vectors.txt with one case per line:

    <name> <cname> <clevel> <shuffle> <typesize> <original-hex> <buffer-hex>

The cases span the container's decode paths: every internal compressor, all three
shuffle modes, several type sizes, buffers small enough to be stored uncompressed
(the memcpy path), and buffers large enough to span multiple blocks.
"""
import os
import random
from numcodecs import Blosc

OUT = os.path.join("core", "src", "test", "resources", "fixtures", "blosc_vectors.txt")

SHUFFLE_NAMES = {Blosc.NOSHUFFLE: "noshuffle", Blosc.SHUFFLE: "shuffle",
                 Blosc.BITSHUFFLE: "bitshuffle"}

CASES = []
rng = random.Random(20260720)


def case(name, data, cname="lz4", clevel=5, shuffle=Blosc.SHUFFLE, typesize=4):
    CASES.append((name, cname, clevel, shuffle, typesize, bytes(data)))


def int32_ramp(n):
    out = bytearray()
    for i in range(n):
        out += (i % 1000).to_bytes(4, "little")
    return bytes(out)


def float64_ramp(n):
    import struct
    out = bytearray()
    for i in range(n):
        out += struct.pack("<d", i * 0.5)
    return bytes(out)


# Every internal compressor, on data that actually compresses. Highly repetitive input is used
# deliberately: on less compressible data blosc gives up and stores the buffer raw (memcpy), which
# would leave the internal decompressors untested.
for cname in ("blosclz", "lz4", "lz4hc", "zlib", "zstd"):
    case(f"{cname}_int32", int32_ramp(2000), cname=cname, typesize=4)
    case(f"{cname}_repetitive", b"abcdefgh" * 2000, cname=cname, typesize=1)
    case(f"{cname}_zeros", bytes(10000), cname=cname, typesize=1)
    case(f"{cname}_text", (b"the quick brown fox jumps over the lazy dog. " * 300),
         cname=cname, typesize=1)
    # long runs with occasional literals: exercises match/literal interleaving
    mixed = bytearray()
    for i in range(600):
        mixed += b"A" * 30 + bytes([(i * 7) % 256, (i * 13) % 256])
    case(f"{cname}_runs", bytes(mixed), cname=cname, typesize=1)

# Shuffle modes.
for shuffle in (Blosc.NOSHUFFLE, Blosc.SHUFFLE, Blosc.BITSHUFFLE):
    case(f"lz4_{SHUFFLE_NAMES[shuffle]}", int32_ramp(1000), shuffle=shuffle, typesize=4)
    case(f"zstd_{SHUFFLE_NAMES[shuffle]}", float64_ramp(1000), cname="zstd",
         shuffle=shuffle, typesize=8)

# Bit-shuffle across type sizes and element counts (multiples of 8 and not), and multi-block sizes.
for ts in (1, 2, 4, 8, 16):
    payload = bytes(rng.randrange(256) for _ in range(ts * 800))  # 800 elements: a multiple of 8
    case(f"bitshuffle_ts{ts}", payload, cname="lz4", shuffle=Blosc.BITSHUFFLE, typesize=ts)
case("bitshuffle_ramp_i32", int32_ramp(2048), cname="lz4", shuffle=Blosc.BITSHUFFLE, typesize=4)
case("bitshuffle_ramp_f64", float64_ramp(2048), cname="zstd", shuffle=Blosc.BITSHUFFLE, typesize=8)
case("bitshuffle_odd_count", int32_ramp(1003), cname="lz4", shuffle=Blosc.BITSHUFFLE, typesize=4)
case("bitshuffle_small", int32_ramp(24), cname="lz4", shuffle=Blosc.BITSHUFFLE, typesize=4)
case("bitshuffle_zstd_zeros", bytes(8000), cname="zstd", shuffle=Blosc.BITSHUFFLE, typesize=8)
case("bitshuffle_multiblock", int32_ramp(200000), cname="lz4", shuffle=Blosc.BITSHUFFLE, typesize=4)

# Type sizes (the shuffle filters and block splitting both depend on this).
for typesize in (1, 2, 4, 8, 16):
    payload = bytes(rng.randrange(64) for _ in range(typesize * 500))
    case(f"typesize{typesize}", payload, typesize=typesize)

# Incompressible data: blosc stores it raw, exercising the memcpy paths.
case("random_small", bytes(rng.randrange(256) for _ in range(64)), typesize=1)
case("random_large", bytes(rng.randrange(256) for _ in range(20000)), typesize=1)

# Degenerate and boundary sizes.
case("empty", b"", typesize=1)
case("one_byte", b"Z", typesize=1)
case("all_same", b"\x7f" * 8192, typesize=1)

# Large enough to span several internal blocks.
case("multiblock_lz4", int32_ramp(200000), cname="lz4", typesize=4)
case("multiblock_zstd", int32_ramp(200000), cname="zstd", typesize=4)
case("multiblock_blosclz", int32_ramp(200000), cname="blosclz", typesize=4)

# Compression levels.
for clevel in (1, 9):
    case(f"lz4_clevel{clevel}", int32_ramp(3000), clevel=clevel, typesize=4)


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# name cname clevel shuffle typesize original-hex buffer-hex\n")
        f.write("# generated by tools/fixtures/gen_blosc_vectors.py (numcodecs/c-blosc)\n")
        for name, cname, clevel, shuffle, typesize, data in CASES:
            codec = Blosc(cname=cname, clevel=clevel, shuffle=shuffle, blocksize=0)
            buf = bytes(codec.encode(data))
            f.write(f"{name} {cname} {clevel} {SHUFFLE_NAMES[shuffle]} {typesize} "
                    f"{data.hex()} {buf.hex()}\n")
            flags = buf[2] if len(buf) > 2 else 0
            print(f"  {name:22s} {cname:8s} ts={typesize:<3d} {len(data):>7d} -> {len(buf):>7d} "
                  f"flags=0x{flags:02x}")
    print(f"{len(CASES)} vectors -> {OUT}")


if __name__ == "__main__":
    main()
