"""Reference vectors for Falcon Core's LZF and bitshuffle decoders, from the real libraries.

LZF is h5py's built-in filter (liblzf); bitshuffle is hdf5plugin's (Kiyoshi Masui's bitshuffle, alone or
with LZ4 or zstd). Each case writes one chunk through the HDF5 filter and reads its stored bytes back with
read_direct_chunk. Dev-time tool (h5py, hdf5plugin); neither is a Falcon dependency.

Writes, under core/src/test/resources/fixtures:
  lzf_vectors.txt          name original-length original-hex lzf-hex
  bitshuffle_vectors.txt   name element-size elements block-size codec original-hex stream-hex
where a compressed bitshuffle stream has the HDF5 filter's 12-byte header (decoded size, block bytes)
removed, its block size taken from that header.

Usage (from the repo root):  python tools/fixtures/gen_core_vectors.py
"""
import io
import os
import struct

import h5py
import hdf5plugin
import numpy as np

OUT = os.path.join("core", "src", "test", "resources", "fixtures")


def _chunk(data, **filters):
    """The stored bytes of one chunk holding all of ``data``, written through ``filters``; None if the
    filter could not shrink it (and so was skipped)."""
    buf = io.BytesIO()
    with h5py.File(buf, "w") as f:
        d = f.create_dataset("d", data=data, chunks=data.shape, **filters)
        mask, raw = d.id.read_direct_chunk((0,) * data.ndim)
        return None if mask else raw


def _arrays():
    rng = np.random.default_rng(7)
    return {
        "int32_ramp": np.arange(1000, dtype="<i4"),
        "float64_noise": np.cumsum(rng.normal(size=600)).astype("<f8"),
        "uint8_odd": (np.arange(1003) % 251).astype("u1"),       # not a multiple of 8 elements
        "int16_text": np.frombuffer((b"the quick brown fox jumps over the lazy dog " * 40)[:1600], dtype="<i2"),
        "int64_random": rng.integers(-2**40, 2**40, size=300).astype("<i8"),  # barely compressible
    }


def lzf_vectors():
    lines = ["# name original-length original-hex lzf-hex",
             "# generated by tools/fixtures/gen_core_vectors.py (h5py's lzf filter, liblzf)"]
    for name, data in _arrays().items():
        raw = _chunk(data, compression="lzf")
        if raw is None:
            continue  # LZF cannot shrink it, so h5py stores the chunk unfiltered
        original = data.tobytes()
        lines.append(f"{name} {len(original)} {original.hex()} {raw.hex()}")
    return lines


def bitshuffle_vectors():
    lines = ["# name element-size elements block-size codec original-hex stream-hex",
             "# generated by tools/fixtures/gen_core_vectors.py (hdf5plugin's bitshuffle filter)"]
    for name, data in _arrays().items():
        for cname, nelems in (("none", 0), ("lz4", 0), ("zstd", 0), ("lz4", 64)):
            raw = _chunk(data, **hdf5plugin.Bitshuffle(nelems=nelems, cname=cname))
            if raw is None:
                raise RuntimeError("bitshuffle skipped a chunk")
            if cname == "none":
                block, stream = nelems, raw
            else:
                size, block_bytes = struct.unpack(">QI", raw[:12])
                if size != data.nbytes:
                    raise RuntimeError("unexpected bitshuffle header")
                block, stream = block_bytes // data.itemsize, raw[12:]
            lines.append(f"{name}_{cname}_{nelems} {data.itemsize} {data.size} {block} {cname} "
                         f"{data.tobytes().hex()} {stream.hex()}")
    return lines


def main():
    os.makedirs(OUT, exist_ok=True)
    for file, lines in (("lzf_vectors.txt", lzf_vectors()), ("bitshuffle_vectors.txt", bitshuffle_vectors())):
        with open(os.path.join(OUT, file), "w", newline="\n") as f:
            f.write("\n".join(lines) + "\n")
        print(f"{len(lines) - 2} vectors -> {os.path.join(OUT, file)}")
    print(f"h5py {h5py.__version__} | hdf5plugin {hdf5plugin.version}")


if __name__ == "__main__":
    main()
