"""Reference vectors for Falcon Core's zfp encoder, from libzfp 1.0.1 itself, through its two users.

Each case compresses one array and records the input and libzfp's stream:
  - h5z: through hdf5plugin's H5Z-ZFP filter (zfp built with 8-bit stream words), the array one chunk; the
    zfp header H5Z-ZFP keeps in the filter's client data, and the chunk, a bare stream, read back with
    read_direct_chunk. H5Z-ZFP sets a fixed rate knowing the scalar type.
  - zfpy: through zfpy.compress_numpy (zfp built with 64-bit words), as numcodecs' zfpy codec calls it: the
    full header and the stream in one. zfpy sets a fixed rate without the type (zfp_type_none).
Every mode, scalar type, and dimensionality is covered, with partial and whole blocks, and values zfp does
not expect (NaN, infinities, subnormals) to pin what libzfp does with them on x86-64. Dev-time tool (h5py,
hdf5plugin, zfpy); none is a Falcon dependency.

Writes core/src/test/resources/fixtures/zfp_encoder_vectors.txt:
  name kind header-hex input-hex stream-hex
where header-hex is H5Z-ZFP's client data values 1 onward as little-endian 32-bit words (the header's bytes),
or "-" for zfpy, and input-hex is the array little-endian, x (the last dimension) fastest.

Usage (from the repo root):  python tools/fixtures/gen_zfp_encoder_vectors.py
"""
import io
import os
import struct

import h5py
import hdf5plugin
import numpy as np
import zfpy
from importlib.metadata import version

OUT = os.path.join("core", "src", "test", "resources", "fixtures", "zfp_encoder_vectors.txt")

PARTIAL = {"1d": (37,), "2d": (9, 7), "3d": (5, 6, 3), "4d": (5, 4, 3, 2)}
WHOLE = {"1dw": (16,), "2dw": (8, 8), "3dw": (4, 4, 8), "4dw": (4, 4, 4, 8)}

H5Z_MODES = {
    "rate2": dict(rate=2.0),
    "rate12": dict(rate=12.0),
    "rate40": dict(rate=40.0),           # in 3 and 4 dimensions maxbits passes 2048: the long mode encoding
    "prec3": dict(precision=3),
    "prec28": dict(precision=28),
    "prec64": dict(precision=64),        # zfp's defaults: expert mode
    "acc1e-2": dict(accuracy=1e-2),
    "acc1e-9": dict(accuracy=1e-9),
    "acc100": dict(accuracy=100.0),      # most blocks need no bit planes
    "rev": dict(reversible=True),
    "expert": dict(minbits=300, maxbits=900, maxprec=40, minexp=-30),
}

ZFPY_MODES = {
    "rate0.25": dict(rate=0.25),         # zfpy gives zfp no type, so no floor: integers only (see below)
    "rate2": dict(rate=2.0),
    "rate12": dict(rate=12.0),
    "rate40": dict(rate=40.0),
    "prec0": dict(precision=0),          # all 64 planes: expert mode
    "prec3": dict(precision=3),
    "prec28": dict(precision=28),
    "acc0": dict(tolerance=0.0),         # every plane: expert mode
    "acc1e-2": dict(tolerance=1e-2),
    "acc1e-9": dict(tolerance=1e-9),
    "acc100": dict(tolerance=100.0),
    "rev": dict(),                       # numcodecs' default (fixed accuracy, tolerance -1)
}

WHOLE_MODES = ("rate12", "prec28", "acc1e-2", "rev")


def _field(shape, dtype, rng):
    grids = np.meshgrid(*[np.linspace(0, 3, n) for n in shape], indexing="ij")
    smooth = sum(np.sin(g * (i + 1)) for i, g in enumerate(grids)) * 1000.0
    noisy = smooth + rng.normal(scale=40.0, size=shape)
    if dtype.kind == "f":
        return noisy.astype(dtype)
    scale = 2 ** 15 if dtype.itemsize == 4 else 2 ** 40  # zfp expects integers well inside their range
    return (noisy * scale / 4000.0).astype(dtype)


def _specials(shape, dtype, rng):
    info = np.finfo(dtype)
    pool = np.array([np.nan, np.inf, -np.inf, -0.0, 0.0, info.tiny, info.tiny / 8, -info.smallest_subnormal,
                     info.max, -info.max, 1.0, -1.5, 3.25e-3], dtype=dtype)
    return rng.choice(pool, size=shape)


def _h5z(data, mode):
    buf = io.BytesIO()
    with h5py.File(buf, "w") as f:
        f.create_dataset("d", data=data, chunks=data.shape, **hdf5plugin.Zfp(**mode))
    with h5py.File(buf, "r") as f:
        d = f["d"]
        plist = d.id.get_create_plist()
        cd = None
        for i in range(plist.get_nfilters()):
            code, _flags, values, _name = plist.get_filter(i)
            if code == hdf5plugin.ZFP_ID:
                cd = values
        mask, raw = d.id.read_direct_chunk((0,) * data.ndim)
        assert mask == 0, "the ZFP filter was skipped"
    return struct.pack(f"<{len(cd) - 1}I", *cd[1:]).hex(), bytes(raw).hex()


def _le(data):
    return data.astype(data.dtype.newbyteorder("<")).tobytes().hex()


def main():
    rng = np.random.default_rng(29)
    lines = ["# name kind header-hex input-hex stream-hex",
             "# generated by tools/fixtures/gen_zfp_encoder_vectors.py (hdf5plugin " + hdf5plugin.version
             + ": H5Z-ZFP 1.1.1, zfp 1.0.1; zfpy " + version("zfpy") + ")"]
    cases = []  # (name, data, h5z mode or None, zfpy mode or None)
    for type_name in ("f4", "f8", "i4", "i8"):
        dtype = np.dtype("<" + type_name)
        for dim_name, shape in list(PARTIAL.items()) + list(WHOLE.items()):
            data = _field(shape, dtype, rng)
            whole = dim_name in WHOLE
            for mode_name, mode in H5Z_MODES.items():
                if not whole or mode_name in WHOLE_MODES:
                    cases.append((f"{type_name}_{dim_name}_{mode_name}", data, mode, None))
            for mode_name, mode in ZFPY_MODES.items():
                if dtype.kind == "f" and "rate" in mode and np.floor(4 ** len(shape) * mode["rate"] + 0.5) < (
                        9 if dtype.itemsize == 4 else 12):
                    continue  # zfp_stream_maximum_size allows fewer bits than the block's exponent: an overrun
                if not whole or mode_name in WHOLE_MODES:
                    cases.append((f"{type_name}_{dim_name}_{mode_name}", data, None, mode))
        # integers at the edges of their range, which only the reversible mode keeps
        if dtype.kind == "i":
            info = np.iinfo(dtype)
            edges = rng.choice(np.array([info.min, info.max, 0, -1, 1, info.min + 1, info.max - 1], dtype), size=(6, 6))
            cases.append((f"{type_name}_2d_rev_edges", edges, dict(reversible=True), None))
            cases.append((f"{type_name}_2d_rev_edges", edges, None, dict()))
    for type_name in ("f4", "f8"):
        dtype = np.dtype("<" + type_name)
        for dim_name in ("1d", "3d"):
            specials = _specials(PARTIAL[dim_name], dtype, rng)
            for mode_name, h5z, zmode in (("rev", dict(reversible=True), dict()),
                                          ("rate16", dict(rate=16.0), dict(rate=16.0)),
                                          ("acc1e-3", dict(accuracy=1e-3), dict(tolerance=1e-3))):
                cases.append((f"{type_name}_{dim_name}_{mode_name}_specials", specials, h5z, None))
                cases.append((f"{type_name}_{dim_name}_{mode_name}_specials", specials, None, zmode))
        zeros = np.zeros((6, 6), dtype)
        negzeros = np.where(rng.random((6, 6)) < 0.3, -0.0, 0.0).astype(dtype)
        tiny = (_field((8, 8), dtype, rng) * np.asarray(1e-300 if type_name == "f8" else 1e-35, dtype)).astype(dtype)
        for data_name, data in (("zero", zeros), ("negzero", negzeros), ("tiny", tiny)):
            for mode_name, h5z, zmode in (("rate8", dict(rate=8.0), dict(rate=8.0)),
                                          ("rev", dict(reversible=True), dict()),
                                          ("acc1e-3", dict(accuracy=1e-3), dict(tolerance=1e-3))):
                cases.append((f"{type_name}_2d_{mode_name}_{data_name}", data, h5z, None))
                cases.append((f"{type_name}_2d_{mode_name}_{data_name}", data, None, zmode))
        cases.append((f"{type_name}_2d_expert_zero", zeros, dict(minbits=200, maxbits=500, maxprec=30, minexp=-10),
                      None))
    for name, data, h5z, zmode in cases:
        if h5z is not None:
            header, stream = _h5z(data, h5z)
            lines.append(f"{name} h5z {header} {_le(data)} {stream}")
        else:
            stream = zfpy.compress_numpy(np.ascontiguousarray(data), write_header=True, **zmode)
            lines.append(f"{name} zfpy - {_le(data)} {bytes(stream).hex()}")
    with open(OUT, "w", newline="\n") as out:
        out.write("\n".join(lines) + "\n")
    print("wrote", len(cases), "vectors to", OUT)


if __name__ == "__main__":
    main()
