"""Generates zstd reference vectors with numcodecs (which wraps libzstd).

Dev-time tool only -- numcodecs is NOT a Falcon dependency, exactly like libaec
for the hdf5 module's szip vectors. Install with:  pip install numcodecs
Run from the repo root:  python tools/fixtures/gen_zstd_vectors.py

Writes zarr/src/test/resources/fixtures/zstd_vectors.txt with one case per line:

    <name> <level> <original-hex> <frame-hex>

The cases deliberately span the format's decode paths: raw blocks, RLE blocks,
Huffman-coded literals in both the single-stream and 4-stream layouts, FSE-coded
sequences, long matches and repeat offsets, and multi-block frames.
"""
import os
import random
from numcodecs import Zstd

OUT = os.path.join("zarr", "src", "test", "resources", "fixtures", "zstd_vectors.txt")

CASES = []


def case(name, data, level=3):
    CASES.append((name, level, bytes(data)))


rng = random.Random(20260720)

# Raw / tiny: incompressible, so libzstd emits a raw block.
case("empty", b"")
case("one_byte", b"A")
case("tiny_random", bytes(rng.randrange(256) for _ in range(16)))
case("small_random", bytes(rng.randrange(256) for _ in range(200)))

# RLE and highly repetitive input: long matches, repeat offsets.
case("all_zeros_64", bytes(64))
case("all_same_4k", b"\x5a" * 4096)
case("repeating_pattern", (b"abcdefgh" * 512))
case("two_phase", (b"x" * 1000) + (b"y" * 1000))

# Text-like: Huffman-coded literals with a skewed symbol distribution.
text = (b"the quick brown fox jumps over the lazy dog. " * 100)
case("text_small", text[:300])
case("text_medium", text)
case("text_large", text * 8)

# Mixed literals + matches, large enough for the 4-stream Huffman layout.
mixed = bytearray()
for i in range(4000):
    mixed += bytes([rng.randrange(64) + 32])
    if i % 7 == 0:
        mixed += b"COMMON_SUBSTRING"
case("mixed_large", bytes(mixed))

# Structured numeric data, the shape a real chunk has.
nums = bytearray()
for i in range(2000):
    nums += (i % 251).to_bytes(4, "little")
case("int32_like", bytes(nums))

# Multi-block: a zstd block caps at 128 KiB, so this frame has several.
big = bytearray()
for i in range(400000):
    big.append((i * 7) % 256)
case("multiblock", bytes(big))

# Compression levels change the encoder's choices (and thus the decode paths).
case("text_level1", text, level=1)
case("text_level9", text, level=9)
case("text_level19", text, level=19)
case("random_level1", bytes(rng.randrange(256) for _ in range(500)), level=1)


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# name level original-hex frame-hex\n")
        f.write("# generated by tools/fixtures/gen_zstd_vectors.py (numcodecs/libzstd)\n")
        for name, level, data in CASES:
            frame = Zstd(level=level).encode(data)
            f.write(f"{name} {level} {data.hex()} {bytes(frame).hex()}\n")
            print(f"  {name:20s} level={level:<3d} {len(data):>7d} -> {len(frame):>7d} bytes")
    print(f"{len(CASES)} vectors -> {OUT}")


if __name__ == "__main__":
    main()
