"""Reference vectors for Falcon Core's LZF and bitshuffle decoders and encoders, from the real libraries.

LZF is h5py's built-in filter (liblzf); bitshuffle is hdf5plugin's (Kiyoshi Masui's bitshuffle, alone or
with LZ4 or zstd). Each case writes one chunk through the HDF5 filter and reads its stored bytes back with
read_direct_chunk. Dev-time tool (h5py, hdf5plugin); neither is a Falcon dependency.

Writes, under core/src/test/resources/fixtures:
  lzf_vectors.txt          name original-length original-hex lzf-hex
  bitshuffle_vectors.txt   name element-size elements block-size codec original-hex stream-hex
where lzf-hex is "-" when liblzf could not fit the stream in the chunk's own size (h5py then stores the
chunk unfiltered), and a compressed bitshuffle stream has the HDF5 filter's 12-byte header (decoded size,
block bytes) removed, its block size taken from that header.

Usage (from the repo root):  python tools/fixtures/gen_core_vectors.py
"""
import io
import os
import struct

import h5py
import hdf5plugin
import numpy as np

OUT = os.path.join("core", "src", "test", "resources", "fixtures")


def _chunk(data, **filters):
    """The stored bytes of one chunk holding all of ``data``, written through ``filters``; None if the
    filter could not shrink it (and so was skipped)."""
    buf = io.BytesIO()
    with h5py.File(buf, "w") as f:
        d = f.create_dataset("d", data=data, chunks=data.shape, **filters)
        mask, raw = d.id.read_direct_chunk((0,) * data.ndim)
        return None if mask else raw


def _arrays():
    rng = np.random.default_rng(7)
    return {
        "int32_ramp": np.arange(1000, dtype="<i4"),
        "float64_noise": np.cumsum(rng.normal(size=600)).astype("<f8"),
        "uint8_odd": (np.arange(1003) % 251).astype("u1"),       # not a multiple of 8 elements
        "int16_text": np.frombuffer((b"the quick brown fox jumps over the lazy dog " * 40)[:1600], dtype="<i2"),
        "int64_random": rng.integers(-2**40, 2**40, size=300).astype("<i8"),  # barely compressible
    }


def _lzf_arrays():
    """For the encoder: inputs from 1 byte to 30 KiB, repeats nearer and farther than LZF's 8 KiB window,
    runs and literals past their 32- and 264-byte limits, and inputs that only just fit, or do not."""
    rng = np.random.default_rng(17)
    arrays = {}
    for n in (1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 16, 37):
        arrays[f"uint8_a{n}"] = np.full(n, 97, dtype="u1")
    arrays["uint8_zeros_16k"] = np.zeros(16384, dtype="u1")
    arrays["int32_period_6k"] = np.tile(rng.integers(0, 2**20, 1536), 4).astype("<i4")
    arrays["int32_period_10k"] = np.tile(rng.integers(0, 2**20, 2560), 3).astype("<i4")
    arrays["float32_walk"] = np.cumsum(rng.normal(size=4096)).astype("<f4")
    words = [b"falcon", b"reads", b"and", b"writes", b"hdf5", b"zarr", b"chunks", b"filters", b"lzf", b"!"]
    text = b" ".join(words[i] for i in rng.integers(0, len(words), 1800))
    arrays["uint8_text"] = np.frombuffer(text, dtype="u1")
    runs = bytearray()
    while len(runs) < 20000:
        runs += bytes([int(rng.integers(0, 256))]) * int(rng.integers(1, 300))
        runs += rng.integers(0, 256, int(rng.integers(0, 70)), dtype="u1").tobytes()
    arrays["uint8_runs"] = np.frombuffer(bytes(runs), dtype="u1")
    # Mostly random bytes with a few repeats: the stream lands near the input's own size, either side of it.
    for i in range(24):
        n = int(rng.integers(40, 3000))
        data = bytearray(rng.integers(0, 256, n, dtype="u1").tobytes())
        for _ in range(int(rng.integers(0, 6))):
            length = int(rng.integers(3, 40))
            src = int(rng.integers(0, n - length))
            dst = int(rng.integers(0, n - length))
            data[dst:dst + length] = data[src:src + length]
        arrays[f"uint8_edge{i}"] = np.frombuffer(bytes(data), dtype="u1")
    return arrays


def lzf_vectors():
    lines = ["# name original-length original-hex lzf-hex",
             "# generated by tools/fixtures/gen_core_vectors.py (h5py's lzf filter, liblzf)"]
    for name, data in {**_arrays(), **_lzf_arrays()}.items():
        raw = _chunk(data, compression="lzf")
        # None: LZF cannot shrink it, so h5py stores the chunk unfiltered
        original = data.tobytes()
        lines.append(f"{name} {len(original)} {original.hex()} {'-' if raw is None else raw.hex()}")
    return lines


def _bitshuffle_cases():
    """The arrays of _arrays() in four forms; then odd element sizes (3, 12, 16 bytes), small and large blocks,
    and element counts around multiples of 8 and of the block."""
    for name, data in _arrays().items():
        for cname, nelems in (("none", 0), ("lz4", 0), ("zstd", 0), ("lz4", 64)):
            yield name, data, cname, nelems
    rng = np.random.default_rng(23)
    walk = np.cumsum(rng.integers(-3, 4, size=3000)).astype("<i4")
    extra = {
        "void3": (np.frombuffer(rng.integers(0, 4, 3 * 341, dtype="u1").tobytes(), dtype="V3"),
                  (("none", 8), ("lz4", 0), ("lz4", 24))),
        "compound12": (np.frombuffer(np.stack([walk[:500], walk[500:1000], walk[1000:1500]], axis=1).tobytes(),
                                     dtype="V12"), (("none", 0), ("lz4", 16))),
        "complex16": (np.exp(1j * np.linspace(0, 20, 263)).astype("<c16"), (("lz4", 0), ("none", 8))),
        "int32_walk": (walk, (("none", 256), ("lz4", 256), ("lz4", 2992), ("lz4", 3000), ("lz4", 8))),
        "uint8_walk": ((walk % 7).astype("u1")[:2051], (("lz4", 2048), ("none", 2048))),
    }
    for name, (data, forms) in extra.items():
        for cname, nelems in forms:
            yield name, data, cname, nelems


def bitshuffle_vectors():
    lines = ["# name element-size elements block-size codec original-hex stream-hex",
             "# generated by tools/fixtures/gen_core_vectors.py (hdf5plugin's bitshuffle filter)"]
    for name, data, cname, nelems in _bitshuffle_cases():
        raw = _chunk(data, **hdf5plugin.Bitshuffle(nelems=nelems, cname=cname))
        if raw is None:
            raise RuntimeError("bitshuffle skipped a chunk")
        if cname == "none":
            block, stream = nelems, raw
        else:
            size, block_bytes = struct.unpack(">QI", raw[:12])
            if size != data.nbytes:
                raise RuntimeError("unexpected bitshuffle header")
            block, stream = block_bytes // data.itemsize, raw[12:]
        lines.append(f"{name}_{cname}_{nelems} {data.itemsize} {data.size} {block} {cname} "
                     f"{data.tobytes().hex()} {stream.hex()}")
    return lines


def main():
    os.makedirs(OUT, exist_ok=True)
    for file, lines in (("lzf_vectors.txt", lzf_vectors()), ("bitshuffle_vectors.txt", bitshuffle_vectors())):
        with open(os.path.join(OUT, file), "w", newline="\n") as f:
            f.write("\n".join(lines) + "\n")
        print(f"{len(lines) - 2} vectors -> {os.path.join(OUT, file)}")
    print(f"h5py {h5py.__version__} | hdf5plugin {hdf5plugin.version}")


if __name__ == "__main__":
    main()
