"""Reference vectors for Falcon Core's zfp decoder, from libzfp itself (hdf5plugin's H5Z-ZFP filter).

Each case writes one array as a single chunk through the ZFP HDF5 filter (H5Z-ZFP 1.1.1, zfp 1.0.1) and
records the zfp header H5Z-ZFP keeps in the filter's client data, the chunk (the bare zfp stream, read
back with read_direct_chunk), and the values libzfp decodes from it (the dataset read through the filter).
ZFP is lossy, so the decoded values, not the originals, are the reference. Dev-time tool (h5py,
hdf5plugin); neither is a Falcon dependency.

Writes core/src/test/resources/fixtures/zfp_vectors.txt:
  name header-hex stream-hex decoded-hex
where header-hex is client data values 1 onward as little-endian 32-bit words (the header's bytes) and
decoded-hex is the field little-endian, x (the last HDF5 dimension) fastest.

Usage (from the repo root):  python tools/fixtures/gen_zfp_vectors.py
"""
import io
import os
import struct

import h5py
import hdf5plugin
import numpy as np

OUT = os.path.join("core", "src", "test", "resources", "fixtures", "zfp_vectors.txt")

SHAPES = {"1d": (37,), "2d": (9, 7), "3d": (5, 6, 3), "4d": (5, 4, 3, 2)}

MODES = {
    "rate2": dict(rate=2.0),
    "rate12": dict(rate=12.0),
    "rate40": dict(rate=40.0),           # in 3 and 4 dimensions maxbits passes 2048: the long mode encoding
    "prec3": dict(precision=3),
    "prec28": dict(precision=28),
    "prec64": dict(precision=64),
    "acc1e-2": dict(accuracy=1e-2),
    "acc1e-9": dict(accuracy=1e-9),
    "acc100": dict(accuracy=100.0),       # most blocks need no bit planes
    "rev": dict(reversible=True),
    "expert": dict(minbits=300, maxbits=900, maxprec=40, minexp=-30),
}


def _field(shape, dtype, rng):
    grids = np.meshgrid(*[np.linspace(0, 3, n) for n in shape], indexing="ij")
    smooth = sum(np.sin(g * (i + 1)) for i, g in enumerate(grids)) * 1000.0
    noisy = smooth + rng.normal(scale=40.0, size=shape)
    if dtype.kind == "f":
        return noisy.astype(dtype)
    scale = 2 ** 15 if dtype.itemsize == 4 else 2 ** 40  # zfp expects integers well inside their range
    return (noisy * scale / 4000.0).astype(dtype)


def _specials(shape, dtype, rng):
    """Values that only the reversible mode keeps: NaN, infinities, -0, subnormals, extreme magnitudes."""
    info = np.finfo(dtype)
    pool = np.array([np.nan, np.inf, -np.inf, -0.0, 0.0, info.tiny, info.tiny / 8, -info.smallest_subnormal,
                     info.max, -info.max, 1.0, -1.5, 3.25e-3], dtype=dtype)
    return rng.choice(pool, size=shape)


def _encode(data, filt):
    """(header bytes, chunk bytes, libzfp's decoded bytes) of ``data`` as one ZFP chunk."""
    buf = io.BytesIO()
    with h5py.File(buf, "w") as f:
        f.create_dataset("d", data=data, chunks=data.shape, **filt)
    # reopened, so that the values come through the filter rather than from libhdf5's chunk cache
    with h5py.File(buf, "r") as f:
        d = f["d"]
        plist = d.id.get_create_plist()
        cd = None
        for i in range(plist.get_nfilters()):
            code, _flags, values, _name = plist.get_filter(i)
            if code == hdf5plugin.ZFP_ID:
                cd = values
        mask, raw = d.id.read_direct_chunk((0,) * data.ndim)
        assert mask == 0, "the ZFP filter was skipped"
        decoded = d[()]
    header = struct.pack(f"<{len(cd) - 1}I", *cd[1:])
    return header, bytes(raw), decoded.astype(decoded.dtype.newbyteorder("<")).tobytes()


def main():
    rng = np.random.default_rng(13)
    lines = ["# name header-hex stream-hex decoded-hex",
             "# generated by tools/fixtures/gen_zfp_vectors.py (hdf5plugin " + hdf5plugin.version
             + ": H5Z-ZFP 1.1.1, zfp 1.0.1)"]
    cases = []
    for type_name in ("f4", "f8", "i4", "i8"):
        dtype = np.dtype("<" + type_name)
        for dim_name, shape in SHAPES.items():
            data = _field(shape, dtype, rng)
            for mode_name, mode in MODES.items():
                cases.append((f"{type_name}_{dim_name}_{mode_name}", data, mode))
    for type_name in ("f4", "f8"):
        dtype = np.dtype("<" + type_name)
        for dim_name in ("1d", "3d"):
            cases.append((f"{type_name}_{dim_name}_rev_specials", _specials(SHAPES[dim_name], dtype, rng),
                          dict(reversible=True)))
        cases.append((f"{type_name}_2d_rate16_zero", np.zeros((6, 6), dtype), dict(rate=16.0)))
        cases.append((f"{type_name}_2d_expert_zero", np.zeros((6, 6), dtype),
                      dict(minbits=200, maxbits=500, maxprec=30, minexp=-10)))
        cases.append((f"{type_name}_2d_rev_zero", np.zeros((6, 6), dtype), dict(reversible=True)))
        tiny = (_field((8, 8), dtype, rng) * np.asarray(1e-300 if type_name == "f8" else 1e-35, dtype)).astype(dtype)
        cases.append((f"{type_name}_2d_rate8_tiny", tiny, dict(rate=8.0)))
        cases.append((f"{type_name}_2d_rev_tiny", tiny, dict(reversible=True)))
    for name, data, mode in cases:
        header, stream, decoded = _encode(data, hdf5plugin.Zfp(**mode))
        lines.append(f"{name} {header.hex()} {stream.hex()} {decoded.hex()}")
    with open(OUT, "w", newline="\n") as out:
        out.write("\n".join(lines) + "\n")
    print("wrote", len(cases), "vectors to", OUT)


if __name__ == "__main__":
    main()
