"""Generates raw Snappy (block-format) reference vectors for the Blosc snappy codec.

c-blosc's snappy path uses the raw Snappy block format (snappy_uncompress), not the
framing format. Modern c-blosc dropped the snappy compressor, so it can neither
encode it nor round-trip it here; instead these vectors come from `cramjam`
(cramjam.snappy.compress_raw), a dev-time tool that is NOT a Falcon dependency.

Install with:  pip install cramjam
Run from the repo root:  python tools/fixtures/gen_snappy_vectors.py

Writes zarr/src/test/resources/fixtures/snappy_vectors.txt, one case per line:

    <name> <original-hex> <raw-snappy-hex>
"""
import os
import random
import cramjam

OUT = os.path.join("zarr", "src", "test", "resources", "fixtures", "snappy_vectors.txt")

CASES = []
rng = random.Random(20260720)


def case(name, data):
    CASES.append((name, bytes(data)))


case("empty", b"")
case("one", b"A")
case("short", b"hello world")
case("repeats", b"hello hello hello world world world")
case("all_same", b"\x5a" * 4096)
case("pattern", b"abcdefgh" * 512)
case("text", b"the quick brown fox jumps over the lazy dog. " * 100)
case("long_literal", bytes(rng.randrange(256) for _ in range(400)))    # forces multi-byte literal lengths
case("two_phase", (b"x" * 1000) + (b"y" * 1000))
case("mixed", bytes((i * 7) % 251 for i in range(5000)))
case("big", bytes((i // 13) % 256 for i in range(70000)))              # exercises copy offsets/lengths
nums = bytearray()
for i in range(2000):
    nums += (i % 251).to_bytes(4, "little")
case("int32_like", bytes(nums))


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# name original-hex raw-snappy-hex\n")
        f.write("# generated by tools/fixtures/gen_snappy_vectors.py (cramjam)\n")
        for name, data in CASES:
            raw = bytes(cramjam.snappy.compress_raw(data))
            assert bytes(cramjam.snappy.decompress_raw(raw, len(data))) == data
            f.write(f"{name} {data.hex()} {raw.hex()}\n")
            print(f"  {name:14s} {len(data):>7d} -> {len(raw):>7d} bytes")
    print(f"{len(CASES)} vectors -> {OUT}")


if __name__ == "__main__":
    main()
